baseurl = "http://blog.en-g.net/"
languageCode = "ja"
title = "blog.en-g.net"
footnotereturnlinkcontents = "↩"

[params]
author = "en45masao"

[permalinks]
post = "/:year/:month/:day/"

[blackfriday]
extensions = ["definitionLists"]
extensionsmask = ["autoHeaderIds"]
